name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'ui/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'ui/**'
      - '.github/workflows/frontend.yml'

jobs:
  test-frontend:
    name: Frontend Tests & Linting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'ui/package-lock.json'

    - name: Install dependencies
      run: |
        cd ui
        npm install

    - name: Lint code
      run: |
        cd ui
        npm run lint

    - name: Build application
      run: |
        cd ui
        npm run build
      env:
        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: demo-project-id

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: ui/.next/